version: "3.9"
services:
    postgres:
        image: pgvector/pgvector:pg16
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
            POSTGRES_DB: cargorisk
        ports: ["5432:5432"]
        volumes: ["pgdata:/var/lib/postgresql/data"]

    redis:
        image: redis:7
        ports: ["6379:6379"]

    minio:
        image: minio/minio:latest
        command: server /data --console-address ":9001"
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio123
        ports: ["9000:9000", "9001:9001"]
        volumes: ["minio:/data"]

    api:
        build: ./services/api
        env_file: .env
        depends_on: [postgres, redis, minio]
        ports: ["8000:8000"]

    worker:
        build: ./services/worker
        env_file: .env
        depends_on: [api, redis, postgres, minio]

    web:
        build: ./web
        env_file: .env
        depends_on: [api]
        ports: ["3000:3000"]

volumes:
    pgdata:
    minio:
