FROM python:3.11-slim
WORKDIR /app
COPY services/api/requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY services/api /app
CMD ["uvicorn", "app.main:app", "--host","0.0.0.0","--port","8000","--reload"]
