[tool.ruff]
line-length = 100
target-version = "py311"

lint.select = ["E","F","I","B","UP","C4","PIE","RUF"]

# Ignore rules that conflict with FastAPI or are too noisy
lint.ignore = [
  "E501",  # line length
  "B008",  # FastAPI uses Depends/File(...) in defaults
]
lint.isort = { known-first-party = ["app","services"], combine-as-imports = true }
